# Generated by Django 5.2.4 on 2025-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
