# Generated by Django 5.2.4 on 2025-08-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_timetable_room'),
        ('users', '0005_alter_studentprofile_date_of_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsubject',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='users.organization'),
            preserve_default=False,
        ),
    ]
