# Generated by Django 5.2.4 on 2025-08-03 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_academicsession_term'),
        ('users', '0005_alter_studentprofile_date_of_admission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.class')),
                ('form_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_sessions', to='users.teacherprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='users.organization')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.term')),
            ],
            options={
                'ordering': ['-date', 'period'],
                'unique_together': {('organization', 'class_ref', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['session', 'student'],
                'unique_together': {('organization', 'session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.organization')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TermAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('attended_sessions', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='academics.class')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_attendance_summaries', to='users.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='users.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='academics.term')),
            ],
            options={
                'unique_together': {('organization', 'class_ref', 'student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TermClassAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('attended_sessions', models.PositiveIntegerField(default=0)),
                ('male_attendance', models.PositiveIntegerField(default=0)),
                ('female_attendance', models.PositiveIntegerField(default=0)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_class_summaries', to='academics.class')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_class_attendance_summaries', to='users.organization')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_class_attendance_summaries', to='academics.term')),
            ],
            options={
                'unique_together': {('organization', 'class_ref', 'term')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('attended_sessions', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='academics.class')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_attendance_summaries', to='users.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='users.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='academics.term')),
            ],
            options={
                'unique_together': {('organization', 'class_ref', 'student', 'week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyClassAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('attended_sessions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_class_summaries', to='academics.term')),
            ],
            options={
                'unique_together': {('organization', 'class_ref', 'week_start', 'week_end')},
            },
        ),
    ]
