# Generated by Django 5.2.4 on 2025-07-30 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_admission',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='hire_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
