# Generated by Django 5.2.4 on 2025-08-01 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_principalprofile_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_admission',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='hire_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
